DROP TABLE IF EXISTS `anticheat_logs`;
CREATE TABLE `anticheat_logs`  (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `times` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `account` INT(9) NOT NULL,
  `player` VARCHAR(96) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `description` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `position` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `realmId` INT(9) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = INNODB AUTO_INCREMENT = 0 CHARACTER SET = utf8;
